name: elgchat_example
description: Example of using elgchat
homepage: https://github.com/elgansayer/elgchat.git

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.3+3
  google_sign_in: ^4.1.1
  firebase_auth: ^0.15.4
  flutter_bloc: ^6.0.1
  equatable: ^1.2.0
  meta: ^1.1.8
  rxdart: ^0.23.1
  font_awesome_flutter: ^8.4.0
  faker: ^1.2.1
  elgchat:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/
